version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config:/etc/nginx:ro
    networks:
      - webnet
    depends_on:
      - php
      - fe_static
      - mysql

  php:
    # image: php:fpm
    build: 
      dockerfile: ./fastchat_se.dockerfile
      context: ./
    volumes:
      - ./codeignitor:/codeignitor:ro
      - ./php_etc:/usr/local/etc:ro
    networks:
      - webnet
    depends_on:
      - mysql
    # https://github.com/docker-library/php/issues/576
    # user: "1000:1000"

  fe_static:
    image: nginx
    volumes:
      - ../fastchat-fe/dist:/fe_static:ro
      - ../fastchat-fe/fe_static_nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=fastchat
      - MYSQL_PASSWORD=654321
    networks:
      - webnet
    # https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql
    volumes:
      - mysql-datavolume:/var/lib/mysql

volumes:
  mysql-datavolume:

networks:
  webnet:
    driver: bridge