version: "3"
services:
  proxy:
    build: 
      dockerfile: ./fastchat_se_proxy.dockerfile
      context: ./
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - php
      - fe_static
      - mysql

  php:
    build: 
      dockerfile: ./fastchat_se_php.dockerfile
      context: ./
    volumes:
      # bind mount 时注意权限问题：
      # https://stackoverflow.com/questions/29245216/write-in-shared-volumes-docker
      - ./ci_logs:/ci_logs
    networks:
      - webnet
    depends_on:
      - mysql

  fe_static:
    image: nginx
    volumes:
      - ../fastchat-fe/dist:/fe_static:ro
      - ../fastchat-fe/fe_static_nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  mysql:
    build: 
      dockerfile: ./fastchat_se_mysql.dockerfile
      context: ./
    ports:
      - "3306:3306"
    networks:
      - webnet
    volumes:
      - mysql-datavolume:/var/lib/mysql

volumes:
  # 修改配置以后可能需要重建data volume
  # https://github.com/docker-library/mysql/issues/51
  mysql-datavolume:

networks:
  webnet:
    driver: bridge