version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config:/etc/nginx:ro
    networks:
      - webnet
    depends_on:
      - php
      - fe_static

  php:
    # image: php:fpm
    build: 
      dockerfile: ./fastchat_se.dockerfile
      context: ./
    volumes:
      - ./codeignitor:/codeignitor:ro
      - ./php_etc:/usr/local/etc:ro
    networks:
      - webnet
    # https://github.com/docker-library/php/issues/576
    # user: "1000:1000"

  fe_static:
    image: nginx
    volumes:
      - ../fastchat-fe/dist:/fe_static:ro
      - ../fastchat-fe/fe_static_nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge