version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config:/etc/nginx:ro
    networks:
      - webnet
    depends_on:
      - php
      - fe_static
      - mysql

  php:
    # image: php:fpm
    build: 
      dockerfile: ./fastchat_se.dockerfile
      context: ./
    volumes:
      - ./codeigniter:/codeigniter:ro
      - ./php_config/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./ci_logs:/ci_logs
    networks:
      - webnet
    depends_on:
      - mysql
    # https://github.com/docker-library/php/issues/576
    # user: "1000:1000"

  fe_static:
    image: nginx
    volumes:
      - ../fastchat-fe/dist:/fe_static:ro
      - ../fastchat-fe/fe_static_nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fastchat_db
      - MYSQL_USER=fastchat
      - MYSQL_PASSWORD=654321
      # https://github.com/docker-library/mysql/issues/241
      - MYSQL_ROOT_HOST=172.*.*.*
    ports:
      - "3306:3306"
    networks:
      - webnet
    # https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql
    volumes:
      - mysql-datavolume:/var/lib/mysql
      # 修改配置以后可能需要重建data volume
      # https://github.com/docker-library/mysql/issues/51
      - ./mysql_config:/etc/mysql:ro

volumes:
  mysql-datavolume:

networks:
  webnet:
    driver: bridge