version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      # - ./codeignitor:/codeignitor:ro
      - ./nginx_config:/etc/nginx:ro
    networks:
      - webnet
    depends_on:
      - php

  php:
    # image: php:fpm
    build: 
      dockerfile: ./fastchat_se.dockerfile
      context: ./
    volumes:
      - ./codeignitor:/codeignitor:ro
      - ./php_etc:/usr/local/etc:ro
    networks:
      - webnet
    # https://github.com/docker-library/php/issues/576
    # user: "1000:1000"

  fe_static:
    build: 
      dockerfile: ../fastchat-fe/fastchat_fe.dockerfile
      context: ../fastchat-fe
    ports:
      - "8080:80"
    # volumes:
    #   - ./dist:/fe_static:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge