version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./codeignitor:/codeignitor
      - ./nginx_config:/etc/nginx
    networks:
      - webnet
    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - ./codeignitor:/codeignitor
      - ./php_etc:/usr/local/etc
    networks:
      - webnet
    # user: "1000:1000"
networks:
  webnet:
    driver: bridge